{"created": 1754710376.536079, "duration": 2.383294105529785, "exitcode": 1, "root": "/home/jclee/app/blacklist/tests", "environment": {}, "summary": {"passed": 4, "total": 4, "collected": 4}, "collectors": [{"nodeid": "", "outcome": "passed", "result": [{"nodeid": "test_container_system.py", "type": "Module"}]}, {"nodeid": "test_container_system.py", "outcome": "passed", "result": [{"nodeid": "test_container_system.py::test_container_service_registration", "type": "Function", "lineno": 14}, {"nodeid": "test_container_system.py::test_container_singleton_behavior", "type": "Function", "lineno": 57}, {"nodeid": "test_container_system.py::test_container_dependency_injection", "type": "Function", "lineno": 94}, {"nodeid": "test_container_system.py::test_container_error_handling", "type": "Function", "lineno": 144}]}], "tests": [{"nodeid": "test_container_system.py::test_container_service_registration", "lineno": 14, "outcome": "passed", "keywords": ["test_container_service_registration", "test_container_system.py", "__init__.py", "tests"], "setup": {"duration": 0.14168843999505043, "outcome": "passed", "log": [{"name": "src.core.collection_manager.protection_service", "msg": "Error counting recent auth failures: no such table: auth_attempts", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collection_manager/protection_service.py", "filename": "protection_service.py", "module": "protection_service", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 185, "funcName": "_count_recent_auth_failures", "created": 1754710374.5482605, "msecs": 548.0, "relativeCreated": 587.5275135040283, "thread": 138630340677632, "threadName": "MainThread", "processName": "MainProcess", "process": 2856048}, {"name": "src.core.collection_manager.protection_service", "msg": "Error counting recent auth failures: no such table: auth_attempts", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collection_manager/protection_service.py", "filename": "protection_service.py", "module": "protection_service", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 185, "funcName": "_count_recent_auth_failures", "created": 1754710374.548832, "msecs": 548.0, "relativeCreated": 588.0990028381348, "thread": 138630340677632, "threadName": "MainThread", "processName": "MainProcess", "process": 2856048}, {"name": "src.core.collection_manager.protection_service", "msg": "Error counting recent auth failures: no such table: auth_attempts", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collection_manager/protection_service.py", "filename": "protection_service.py", "module": "protection_service", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 185, "funcName": "_count_recent_auth_failures", "created": 1754710374.549058, "msecs": 549.0, "relativeCreated": 588.325023651123, "thread": 138630340677632, "threadName": "MainThread", "processName": "MainProcess", "process": 2856048}, {"name": "src.core.collection_manager.auth_service", "msg": "Error getting auth statistics: no such table: auth_attempts", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collection_manager/auth_service.py", "filename": "auth_service.py", "module": "auth_service", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 172, "funcName": "get_auth_statistics", "created": 1754710374.5493197, "msecs": 549.0, "relativeCreated": 588.5868072509766, "thread": 138630340677632, "threadName": "MainThread", "processName": "MainProcess", "process": 2856048}, {"name": "src.core.collection_manager.auth_service", "msg": "Database error checking auth limits: no such table: auth_attempts", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collection_manager/auth_service.py", "filename": "auth_service.py", "module": "auth_service", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 52, "funcName": "check_auth_attempt_limit", "created": 1754710374.5496519, "msecs": 549.0, "relativeCreated": 588.918924331665, "thread": 138630340677632, "threadName": "MainThread", "processName": "MainProcess", "process": 2856048}, {"name": "src.core.collection_manager.auth_service", "msg": "Error getting auth statistics: no such table: auth_attempts", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collection_manager/auth_service.py", "filename": "auth_service.py", "module": "auth_service", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 172, "funcName": "get_auth_statistics", "created": 1754710374.5498772, "msecs": 549.0, "relativeCreated": 589.144229888916, "thread": 138630340677632, "threadName": "MainThread", "processName": "MainProcess", "process": 2856048}, {"name": "src.core.collection_manager.auth_service", "msg": "Database error checking auth limits: no such table: auth_attempts", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collection_manager/auth_service.py", "filename": "auth_service.py", "module": "auth_service", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 52, "funcName": "check_auth_attempt_limit", "created": 1754710374.5501897, "msecs": 550.0, "relativeCreated": 589.4567966461182, "thread": 138630340677632, "threadName": "MainThread", "processName": "MainProcess", "process": 2856048}, {"name": "src.core.collection_manager.auth_service", "msg": "Error getting auth statistics: no such table: auth_attempts", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/jclee/app/blacklist/src/core/collection_manager/auth_service.py", "filename": "auth_service.py", "module": "auth_service", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 172, "funcName": "get_auth_statistics", "created": 1754710374.5504336, "msecs": 550.0, "relativeCreated": 589.7006988525391, "thread": 138630340677632, "threadName": "MainThread", "processName": "MainProcess", "process": 2856048}]}, "call": {"duration": 0.0027996600256301463, "outcome": "passed", "stdout": "\ud83e\udde0 \ucee8\ud14c\uc774\ub108 \uc11c\ube44\uc2a4 \ub4f1\ub85d/\ud574\uacb0 \ud14c\uc2a4\ud2b8 \uc2dc\uc791...\n  \u2705 blacklist_manager: \uc131\uacf5\n  \u2705 cache_manager: \uc131\uacf5\n  \u2705 auth_manager: \uc131\uacf5\n  \u2705 config: \uc131\uacf5\n  \u2705 metrics_collector: \uc131\uacf5\n  \u2705 health_checker: \uc131\uacf5\n\u2705 \ucee8\ud14c\uc774\ub108 \uc11c\ube44\uc2a4 \ub4f1\ub85d/\ud574\uacb0 \ud14c\uc2a4\ud2b8 \ud1b5\uacfc (6/6)\n"}, "teardown": {"duration": 0.0003641739604063332, "outcome": "passed"}}, {"nodeid": "test_container_system.py::test_container_singleton_behavior", "lineno": 57, "outcome": "passed", "keywords": ["test_container_singleton_behavior", "test_container_system.py", "__init__.py", "tests"], "setup": {"duration": 0.0014217509888112545, "outcome": "passed"}, "call": {"duration": 0.000199940986931324, "outcome": "passed", "stdout": "\ud83e\udde0 \ucee8\ud14c\uc774\ub108 \uc2f1\uae00\ud1a4 \ub3d9\uc791 \ud14c\uc2a4\ud2b8 \uc2dc\uc791...\n  \u2705 \ucee8\ud14c\uc774\ub108 \uc790\uccb4 \uc2f1\uae00\ud1a4 \ub3d9\uc791 \ud655\uc778\n  \u2705 \uc11c\ube44\uc2a4 \uc2f1\uae00\ud1a4 \ub3d9\uc791 \ud655\uc778\n\u2705 \ucee8\ud14c\uc774\ub108 \uc2f1\uae00\ud1a4 \ub3d9\uc791 \ud14c\uc2a4\ud2b8 \uc644\ub8cc\n"}, "teardown": {"duration": 0.0002439150121062994, "outcome": "passed"}}, {"nodeid": "test_container_system.py::test_container_dependency_injection", "lineno": 94, "outcome": "passed", "keywords": ["test_container_dependency_injection", "test_container_system.py", "__init__.py", "tests"], "setup": {"duration": 0.0013899500481784344, "outcome": "passed"}, "call": {"duration": 0.0007909589912742376, "outcome": "passed", "stdout": "\ud83e\udde0 \ucee8\ud14c\uc774\ub108 \uc758\uc874\uc131 \uc8fc\uc785 \ud14c\uc2a4\ud2b8 \uc2dc\uc791...\n  \ud83d\udcc1 \ub4f1\ub85d\ub41c \uc11c\ube44\uc2a4 \uc218: 12\n  \u2705 blacklist_manager: \uc0ac\uc6a9 \uac00\ub2a5\n  \u2705 cache_manager: \uc0ac\uc6a9 \uac00\ub2a5\n  \u2705 auth_manager: \uc0ac\uc6a9 \uac00\ub2a5\n\u2705 \uc758\uc874\uc131 \uc8fc\uc785 \ud14c\uc2a4\ud2b8 \ud1b5\uacfc (3/3)\n"}, "teardown": {"duration": 0.00024139101151376963, "outcome": "passed"}}, {"nodeid": "test_container_system.py::test_container_error_handling", "lineno": 144, "outcome": "passed", "keywords": ["test_container_error_handling", "test_container_system.py", "__init__.py", "tests"], "setup": {"duration": 0.0014139870181679726, "outcome": "passed"}, "call": {"duration": 0.0002771689905785024, "outcome": "passed", "stdout": "\ud83e\udde0 \ucee8\ud14c\uc774\ub108 \uc5d0\ub7ec \ucc98\ub9ac \ud14c\uc2a4\ud2b8 \uc2dc\uc791...\n  \u274c \uc5c6\ub294 \uc11c\ube44\uc2a4\uc5d0 \ub300\ud574 \uc608\uc678\uac00 \ubc1c\uc0dd\ud558\uc9c0 \uc54a\uc74c\n"}, "teardown": {"duration": 0.0002545850002206862, "outcome": "passed"}}]}